nav:
  - Getting Started: index.md
  - Philosophy: philosophy.md
  - Limitations: limitations.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE-OF-CONDUCT.md
  - Changelog: CHANGELOG.md
  - GitHub Source Code: https://github.com/wtc-cloud-eng/mkdocs-terraform-monorepo-plugin


site_name: "mkdocs-terraform-monorepo-plugin (&beta;)"
repo_url: https://github.com/wtc-cloud-eng/mkdocs-terraform-monorepo-plugin
repo_name: 'wtc-cloud-eng/mkdocs-terraform-monorepo-plugin'
site_description: |
  Docs for the mkdocs terraform monorepo plugin - a plugin to include terraform docs in a the navigation


# Copyright
copyright: Copyright © 2021. Wunderman Thompson Commerce - a WPP Company. All rights reserved

# Configuration
theme:
  name: material
  features:
    - tabs
  language: en
  palette:
    primary: deep purple
    accent: teal
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/img/logo.png
  favicon: assets/img/favicon.png

# Extensions
markdown_extensions:
  - markdown_include.include:
      base_path: docs
  - smarty
  - sane_lists
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
